#!/bin/bash

SCRIPT_DIR="$(dirname "$(realpath "$0")")"
DATA_DIR="$SCRIPT_DIR/../data"
ACT_DIR="$SCRIPT_DIR/../module/act"


function existing_act()
{
    file="$ACT_DIR"/$(ls "$ACT_DIR" | sort -R | head -1)

    title="$(head -1 "$file" | sed 's/# //')"
    stats=$(sed -n '/Setting/,+2p' "$file" | sed 's/[ |-]\+/\n/g' | sed '/^\s*$/d' )

    stats=$(paste <(head -3 <<< "$stats") <(tail -3 <<< "$stats") | column -t )

    goals=$(sed -n 's/\*\*Goal\*\*://p' "$file" | tail -n +2 | nl -w 4 -s " - ")
    structure="$(sed -n '/Schematic/,/Scenes/p' "$file" | sed '1d;$d')\n"

    printf "$title\n"
    printf "$stats\n"
    printf "$structure\n"
    printf "$goals\n"
}


function blank_act()
{
    cat <<EOF
# ACT: Act Name

| Setting  | Enemy    | Theme    |
|----------|----------|----------|
|          |          |          |

**Goal**: Act main goal

Brief description of act

## Schematic

      _____               _____
     |     |             |     |
    =|     |    _____    |     |=
     |_____|   |     |   |_____|
               |     |
               |_____|

## Scenes

### 1. First Scene Name

**Goal**: First scene goal

Very short description

- **Point of Interest** and any mechanics that relate to it

Further notes or description

### 2. Second Scene Name

**Goal**: Second scene goal

Very short description

- **Point of Interest** and any mechanics that relate to it

Further notes or description

### 3. Third Scene Name

**Goal**: Third scene goal

Very short description

- **Point of Interest** and any mechanics that relate to it

Further notes or description

### [!] Central tension

Very short description

- **Point of Interest** and any mechanics that relate to it

Further notes or description
EOF
}


function random_act()
{
    title="ACT: Randomly Generated"

    setting="Setting $(sort -R "$DATA_DIR/setting.md" | head -1 )"
    opponent="Enemy $(sort -R "$DATA_DIR/enemy.md" | head -1 )"
    theme="Theme $(sort -R "$DATA_DIR/theme.md" | head -1 )"
    stats=$(printf "$setting\n$opponent\n$theme\n" | column -t )

    structure="$($SCRIPT_DIR/structure 0)\n"

    all_goals=$(sort -R "$DATA_DIR/goal.md")
    goals=""
    for i in 1 2 3; do
        goal="$(head -1 <<< "$all_goals")"
        all_goals="$(tail -n +2 <<< "$all_goals")"
        goals="$goals$goal\n"
    done
    goals=$(printf "$goals" | nl -w 4 -s " - ")

    printf "$title\n"
    printf "$stats\n"
    printf "$structure\n"
    printf "$goals\n"
}

[[ "$1" == "-r" ]] && random_act && exit 0
[[ "$1" == "-e" ]] && existing_act && exit 0
[[ "$1" == "-b" ]] && blank_act && exit 0

