#!/bin/bash

SCRIPT_DIR="$(dirname "$(realpath "$0")")"
DATA_DIR="$SCRIPT_DIR/../data"

STRUCTURE_PATTERN=$(cat <<EOF
      _____               _____
     |     |aaaaaaDaaaaaa|     |
    =|  A  |    _____    |  C  |=
     |_____|bbb|     |ccc|_____|
               |  B  |
               |_____|
EOF
)

function gen_three() {
    struct="$STRUCTURE_PATTERN"
    r=$(($RANDOM % 4))

    remove=""
    [[ $r == "0" ]] && remove+="aD"
    [[ $r == "1" ]] && remove+="b"
    [[ $r == "2" ]] && remove+="c"

    struct=$(tr "$remove" " " <<< "$struct")
    tensions=$(tr -cd "ABCD" <<< "$struct")
    i=$(($RANDOM % ${#tensions}))
    tension=${tensions:$i:1}
    struct=$(sed "s/.$tension./[!]/" <<< "$struct")
    struct=$(tr "ABC" " " <<< "$struct")
    struct=$(tr "Dabc" "=" <<< "$struct")
    printf "$struct"
}

[[ "$1" == "0" ]] && echo "$(gen_three)"
