#!/bin/bash

SCRIPT_DIR="$(dirname "$(realpath "$0")")"
DATA_DIR="$SCRIPT_DIR/../data"

mag="$1"
[[ ! "$mag" =~ ^[0-2]$ ]] && exit 1

function gen_three() {
    struct=$(cat <<EOF
          _____                   _____
         |1    |aaaaaaaaDaaaaaaaa|3    |
        =|  A  |      _____      |  C  |=
         |_____|bbbbb|2    |ccccc|_____|
                     |  B  |
                     |_____|
EOF
)
    r=$(($RANDOM % 4))

    patt=""
    [[ $r == "0" ]] && patt+="aD"
    [[ $r == "1" ]] && patt+="b"
    [[ $r == "2" ]] && patt+="c"

    struct=$(tr "$patt" " " <<< "$struct")
    tensions=$(tr -cd "ABCD" <<< "$struct")
    i=$(($RANDOM % ${#tensions}))
    tension=${tensions:$i:1}
    struct=$(sed "s/.$tension./[X]/" <<< "$struct")
    struct=$(tr "ABC" " " <<< "$struct")
    struct=$(tr "Dabc" "=" <<< "$struct")
    echo "$struct"
}

[[ $mag == "0" ]] && echo "$(gen_three)"
